/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gmail_constants.h"

namespace gmail_master_server {

const gmailConstants g_gmail_constants;

gmailConstants::gmailConstants() {
}

} // namespace

