/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gmail_CONSTANTS_H
#define gmail_CONSTANTS_H

#include "gmail_types.h"

namespace gmail_master_server {

class gmailConstants {
 public:
  gmailConstants();

};

extern const gmailConstants g_gmail_constants;

} // namespace

#endif
